### ISSUE TITLE
Infinite Gear Climbing

### ISSUE THREAD

**Issue by QueryMarks** [das446/Gearmania#2]
It's possible to retrieve and drop the gear quickly after jumping to climb any height with the gear. Here's an image of how high I could get the gear with this technique after about 3 minutes of practice. Basically, the inputs are jump, then double tap z to retrieve and drop the gear right at the start of the jump. All you have to do then is hold towards the gear for a small amount of time while rising and then land on the top of the gear.
![image](https://user-images.githubusercontent.com/5302595/40076804-e1da6f26-584d-11e8-8b78-1e0c22dd7faa.png)

**Comment by das446** [comment]
This happens because the way jumping currently works is that there is a grounded bool to determine if they can jump, which gets set to false whenever the user jumps. It gets set to true whenever the player makes contact with any object in any way. To fix this I will need to implement each object's on collision enter seperately, which shouldn't take too long because I have another project where I did the same thing.

**Comment by das446** [comment]
Fixed this in most recent commit
